### ISSUE TITLE
RIO Heartbeat Message

### ISSUE THREAD

**Issue by Diverjim84** [ThadHouse/FRC-CAN-Arduino#1]
Thad, sorry for using the Issue tracker to reach out, but I'm unsure how else to reach you.  

I'm trying to find more details about the heartbeat 50Hz message the Rio sends outside of what is given in the arbitration schema document on the WPILib Docs. 

Thanks
Jim

**Comment by ThadHouse** [comment]
Do you mean this doc?
https://docs.wpilib.org/en/stable/docs/software/can-devices/can-addressing.html#universal-heartbeat

Thats the hearbeat. The other bytes are not documented, and iirc they're just can status data. The only byte that matters to using it as a heartbeat is the byte listed.

**Comment by Diverjim84** [comment]
Darn, it looked like it was giving some data like a clock.  Trying to figure out a way to do a time sync (like NTP) on CAN.  I was hoping there was something halfway implemented.
